# Generated by Django 4.0.3 on 2022-03-12 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(max_length=50)),
                ('interacao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('anexo', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=300)),
                ('descricao', models.TextField()),
                ('data_abertura', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
                ('prioridade', models.CharField(choices=[('1', 'Baixa'), ('2', 'Média'), ('3', 'Alta')], max_length=1)),
                ('anexo', models.FileField(upload_to='uploads/')),
                ('interacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptkt.interacoes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
