# Generated by Django 4.0.3 on 2022-03-12 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptkt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='interacao',
        ),
        migrations.AddField(
            model_name='interacoes',
            name='chamado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ptkt.tickets'),
            preserve_default=False,
        ),
    ]
