# Generated by Django 4.0.3 on 2022-03-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptkt', '0003_alter_tickets_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacoes',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='prioridade',
            field=models.CharField(max_length=10),
        ),
    ]
